name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg-version: ['12', '13', '14', '15', '16', '17']

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Use Cachix Cache
        uses: cachix/cachix-action@v10
        with:
          name: nxpg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build
        run: nix-shell --run "xpg -v ${{ matrix.pg-version }} build"

      - name: Run tests
        run: nix-shell --run "xpg -v ${{ matrix.pg-version }} test"

      - if: ${{ failure() }}
        run: |
          cat regression.out
          cat regression.diffs

  loadtest:
    strategy:
      matrix:
        kind: ['csv_agg', 'csv_agg_delim', 'csv_agg_delim_bom_nullstr', 'postgrest']
    name: Loadtest
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Use Cachix Cache
        uses: cachix/cachix-action@v10
        with:
          name: nxpg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run loadtest
        run: nix-shell --run "pg_csv-loadtest ${{ matrix.kind }}" >> "$GITHUB_STEP_SUMMARY"

  coverage:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        pg-version: ['17']

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Use Cachix Cache
        uses: cachix/cachix-action@v10
        with:
          name: nxpg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run coverage
        run: nix-shell --run "xpg -v ${{ matrix.pg-version }} coverage"

      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: ./build-${{ matrix.pg-version }}/coverage.info

  style:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Use Cachix Cache
        uses: cachix/cachix-action@v10
        with:
          name: nxpg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run style check
        run: nix-shell --run "pg_csv-style-check"
